# Generated by Django 4.2.4 on 2023-12-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_car_model_car_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_model',
            name='car_price',
            field=models.FloatField(default=0, max_length=50),
        ),
    ]
