# Generated by Django 4.2.4 on 2023-12-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_car_model_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_model',
            name='car_year',
            field=models.CharField(default='', max_length=4),
        ),
    ]
