# Generated by Django 4.2.4 on 2023-12-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_car_model_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_model',
            name='car_uid',
            field=models.CharField(default='', max_length=10),
        ),
    ]
