# Generated by Django 4.2.4 on 2023-12-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_car_model_car_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessary_uid', models.CharField(default='', max_length=10)),
                ('accessary_name', models.CharField(default='', max_length=50)),
                ('accessary_company', models.CharField(max_length=50)),
                ('accessary_price', models.FloatField(max_length=50)),
                ('accessary_info', models.TextField(max_length=200)),
                ('accessary_images', models.ImageField(default=None, upload_to='images/%y/%m/%d')),
                ('slug', models.SlugField(unique=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-upload_date',),
            },
        ),
        migrations.AlterField(
            model_name='car_model',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
