# Generated by Django 4.2.4 on 2023-12-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_accessary_alter_car_model_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_model',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, unique=True),
        ),
    ]
