# Generated by Django 4.2.4 on 2023-12-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_accessary_slug_alter_car_model_car_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_model',
            name='car_uid',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
    ]
