# Generated by Django 4.2.4 on 2023-12-06 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_car_model_car_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_model',
            name='car_mini_image',
        ),
    ]
