# Generated by Django 4.2.4 on 2023-12-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_car_model_car_mini_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_model',
            name='car_uid',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
