# Generated by Django 4.2.4 on 2023-12-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_car_model_car_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessary',
            name='accessary_uid',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='car_model',
            name='car_uid',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
