# Generated by Django 4.2.4 on 2023-12-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_accessary_accessary_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_model',
            name='car_images',
            field=models.ImageField(default='https://t3.ftcdn.net/jpg/01/71/13/24/360_F_171132449_uK0OO5XHrjjaqx5JUbJOIoCC3GZP84Mt.jpg', upload_to='images/%y/%m/%d'),
        ),
    ]
