# Generated by Django 4.2.4 on 2023-12-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_car_model_car_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessary',
            name='accessary_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='car_model',
            name='car_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
