# Generated by Django 4.2.4 on 2023-12-12 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_car_model_car_images'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_accessary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('accessary_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessary_items', to='product.accessary')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_accessary_items', to='cart.cart')),
            ],
        ),
    ]
